### PR TITLE
Add GHAs to repository

### PR DESCRIPTION
**Pull request by gab-arrobo**

### CODE REVIEW

**Review by daf-LF — COMMENTED** [review]
dependabot:   Copyright 2022? Doesn't that need to be 2024?   New file right?

push.yml:  not a breaker, but I worry a little about a regex on tags of 'v*', would 'v\d' or similar be somewhat less prone to accidents?

Dockerfile -- needs update on Copyright (as was done on Makefile)

**Review by thakurajayL — DISMISSED** [review]

**Comment by gab-arrobo** [comment]
> dependabot: Copyright 2022? Doesn't that need to be 2024? New file right?
> 
> push.yml: not a breaker, but I worry a little about a regex on tags of 'v*', would 'v\d' or similar be somewhat less prone to accidents?
> 
> Dockerfile -- needs update on Copyright (as was done on Makefile)

@daf-LF please see latest changes. Regarding the `v*`, that is what we are using in all of the repos. Should it be something like this `v*.*.*`? We follow the semver format v#.#.#

**Comment by daf-LF** [comment]
concerning v*;    my concern is for some doofus at some point accidently adding a tag of "victor-fix-1' or similar.   Perhaps it would be best to have a v*.*.* or whatever the correct regex is for the version expansion to enforce digits and explicit '.'s;   We're <probably> good with v*, as I think there is another check during release process to ensure the tag is a semver, so I would hope any actual action would fail, but you never know.


Copyrights are so ... fuzzy.    The formal legal need is fairly flexible, but it seems like everybody's lawyers have their own version.   The big things are to 
A) Don't remove any pre-existing copyright information in a file.  (you can reformat to simplify or consolidate, but no data loss)
B) Ideally, update whenever editting any file (or adding new files) by adding the current year.

Accordingly, my issue with Dockerhub is the NEW line (#2)  that states an Intel copyright of 2019.   This is a new line, using the SPDX format of Copyright.  Legally, I would either remove the initial raw line at 1 that says 2019, and change the line to 
# SPDX-FileCopyrightText: 2019-2024 Intel Corporation
OR 
keep line 1 but change 2019 to 2024 in line 2.    Either change maintains the copyright history itself.

The second option above is consistent with the Makefile so that's probably best.
NOTE -- almost all of this is pedantic -- Ultimately, it is incredibly rare that any of this matters.   I just got burned bigtime a couple of years ago with a semi-related issue (not precisely copyright, but license/copyright contention) and once I get into this, it becomes a soapbox of mine.     As long as a copyright EXISTS, your legal team can probably handle any future needs.

**Review by daf-LF — APPROVED** [review]
Anyway -- I have no further issues with the code itself

**Comment by gab-arrobo** [comment]
> Copyrights are so ... fuzzy. The formal legal need is fairly flexible, but it seems like everybody's lawyers have their own version. The big things are to A) Don't remove any pre-existing copyright information in a file. (you can reformat to simplify or consolidate, but no data loss) B) Ideally, update whenever editting any file (or adding new files) by adding the current year.
> 
> Accordingly, my issue with Dockerhub is the NEW line (#2) that states an Intel copyright of 2019. This is a new line, using the SPDX format of Copyright. Legally, I would either remove the initial raw line at 1 that says 2019, and change the line to
> 
> # SPDX-FileCopyrightText: 2019-2024 Intel Corporation
> OR keep line 1 but change 2019 to 2024 in line 2. Either change maintains the copyright history itself.
> 
> The second option above is consistent with the Makefile so that's probably best. NOTE -- almost all of this is pedantic -- Ultimately, it is incredibly rare that any of this matters. I just got burned bigtime a couple of years ago with a semi-related issue (not precisely copyright, but license/copyright contention) and once I get into this, it becomes a soapbox of mine. As long as a copyright EXISTS, your legal team can probably handle any future needs.

What about the following?
```diff
-# Copyright (c) 2019 Intel Corporation
+# Copyright (c) 2019-present Intel Corporation
```

**Comment by gab-arrobo** [comment]
> concerning v*; my concern is for some doofus at some point accidently adding a tag of "victor-fix-1' or similar. Perhaps it would be best to have a v*._._ or whatever the correct regex is for the version expansion to enforce digits and explicit '.'s; We're good with v*, as I think there is another check during release process to ensure the tag is a semver, so I would hope any actual action would fail, but you never know.

@daf-LF, Look at this link regarding the `tag` (regex): https://github.com/orgs/community/discussions/55854

**Review by daf-LF — APPROVED** [review]
-present is trouble-some.   Provided copyrights are intended to provide the dates when changes were last done on the work.  IE -- the copyright lifetime STARTS(over if applicable) at the last date shown.   They are presumed to last X years after that (X being somewhat different between kinds of work).   When I last look seriously, the X for software code was 17 years, but I can't find anything definitivie now about software.

Adding -present is implying that updates may have been updated anytime between the first date identified and <whenever a reader is looking at it>, which is NOT the intent of copyrights.


Concerning regex.   Wow, the suggested regex's in the link are quite impressive.  I didn't realize that doing it really right is so much more cumbersome.      Screw it, I formally shut up and say --- Ignore my comments on this.   We'll worry about it if somebody screws it up sometime in the future.  (and probably even then decide it isn't worth adding it everywhere it would be pertinent if the issues only happen every other year or something similar

**Comment by daf-LF** [comment]
erp.  anytime between last date specific and "whenever the reader is looking at the code"

**Pull request merged**
